# Generated by Django 3.1.6 on 2021-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('birthdate', models.DateField(auto_now_add=True)),
                ('subject', models.TextField(max_length=1000)),
                ('roll_num', models.IntegerField(max_length=5)),
            ],
        ),
    ]
