# Generated by Django 3.1.6 on 2021-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUDCreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_num',
            field=models.IntegerField(),
        ),
    ]
