# Generated by Django 3.1.7 on 2021-02-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCRUDCreate', '0006_auto_20210222_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='noimg.png', null=True, upload_to='profile_image/'),
        ),
    ]
